"""
Stage 3: lens distortion correction via ChArUco board calibration.

A ChArUco board (a checkerboard with embedded ArUco markers) is used
instead of a plain checkerboard: partial/angled views still contribute
usable corners since each square is individually identifiable by its
marker, unlike a plain checkerboard which needs the whole grid visible
and unambiguous in every captured frame.

Board parameters (grid size, square/marker length, ArUco dictionary) are
never hardcoded here -- they're passed into CharucoCalibrator's
constructor, driven by the Calibration tab's input fields, since the
physical board in use may change later (e.g. the initial board is 8x8
squares/20mm/15mm, but this needs to keep working for a 6x6 board or a
different dictionary without code changes).

API note: this targets OpenCV 5.0's cv2.aruco surface, confirmed directly
against the installed version -- there is no cv2.aruco.calibrateCameraCharuco
in this version (present in older OpenCV, removed here). The current
pattern is CharucoBoard.matchImagePoints() per view, accumulated, then a
single plain cv2.calibrateCamera() call -- verified end-to-end against a
synthetically rendered/warped ChArUco board before being used here.
"""

from __future__ import annotations

import json
from pathlib import Path

import cv2
import cv2.aruco as aruco
import numpy as np

DEFAULT_CALIBRATION_PATH = Path(__file__).parent / "calibration_data.json"

# 4 (the old minimum) is enough to make cv2.calibrateCamera converge to
# *something*, but with a 9-parameter free model (fx, fy, cx, cy + 5
# distortion coefficients) 4 views is badly underconstrained -- confirmed
# directly against a real saved calibration that used exactly 4 views:
# fx/fy came out around 5500 (implies a telephoto FOV on a wide-angle
# webcam lens) and k3 came out around -39896 (real lenses are within a
# couple orders of magnitude of 1). Low reprojection error on those same
# 4 views doesn't catch this -- it's overfit to them, and produces wild,
# non-physical remapping everywhere else, which is what "undistort makes
# it worse, things shrink/rotate" actually was.
MIN_CALIBRATION_VIEWS = 15

ARUCO_DICTIONARIES = {
    "DICT_4X4_50": aruco.DICT_4X4_50,
    "DICT_4X4_100": aruco.DICT_4X4_100,
    "DICT_4X4_250": aruco.DICT_4X4_250,
    "DICT_5X5_50": aruco.DICT_5X5_50,
    "DICT_5X5_100": aruco.DICT_5X5_100,
    "DICT_5X5_250": aruco.DICT_5X5_250,
    "DICT_6X6_50": aruco.DICT_6X6_50,
    "DICT_6X6_100": aruco.DICT_6X6_100,
    "DICT_6X6_250": aruco.DICT_6X6_250,
    "DICT_7X7_50": aruco.DICT_7X7_50,
    "DICT_7X7_100": aruco.DICT_7X7_100,
    "DICT_ARUCO_ORIGINAL": aruco.DICT_ARUCO_ORIGINAL,
}


class CharucoCalibrator:
    """
    Accumulates ChArUco corner detections across multiple captured
    frames, then runs calibration once enough views are collected. All
    board parameters are set at construction, driven by the Calibration
    tab's input fields.
    """

    def __init__(
        self,
        squares_x: int,
        squares_y: int,
        square_length_mm: float,
        marker_length_mm: float,
        dictionary_name: str = "DICT_5X5_100",
        legacy_pattern: bool = False,
    ) -> None:
        self.squares_x = squares_x
        self.squares_y = squares_y
        self.square_length_mm = square_length_mm
        self.marker_length_mm = marker_length_mm
        self.dictionary_name = dictionary_name
        self.legacy_pattern = legacy_pattern

        self.dictionary = aruco.getPredefinedDictionary(ARUCO_DICTIONARIES[dictionary_name])
        self.board = aruco.CharucoBoard(
            (squares_x, squares_y),
            square_length_mm,
            marker_length_mm,
            self.dictionary,
        )
        # OpenCV changed the ChArUco corner/marker layout convention
        # around 4.6 (fixing a geometric inconsistency in the original
        # pattern). Boards generated by another tool/OpenCV version may
        # still use the old ("legacy") layout -- confirmed directly that
        # this causes markers to detect fine (dictionary-based, layout-
        # independent) while charuco corner interpolation silently
        # returns zero corners, since it's matching against the wrong
        # expected geometry. If markers are found but corners aren't,
        # this is the first thing to try.
        self.board.setLegacyPattern(legacy_pattern)
        self.detector = aruco.CharucoDetector(
            self.board,
            aruco.CharucoParameters(),
            aruco.DetectorParameters(),
        )

        self.object_points_list: list = []
        self.image_points_list: list = []
        self.capture_corner_counts: list[int] = []
        self.image_size: tuple[int, int] | None = None

    def detect(self, frame: np.ndarray) -> dict:
        """
        Runs ChArUco detection on a frame without adding it to the
        calibration set -- used for the live "is the board visible"
        preview. Returns detected corners/ids (possibly None) and an
        annotated BGR copy for on-screen feedback.
        """
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) if frame.ndim == 3 else frame

        charuco_corners, charuco_ids, marker_corners, marker_ids = self.detector.detectBoard(gray)

        annotated = frame.copy() if frame.ndim == 3 else cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)

        if marker_ids is not None and len(marker_ids) > 0:
            try:
                aruco.drawDetectedMarkers(annotated, marker_corners, marker_ids)
            except cv2.error:
                pass  # drawing only; never let an annotation failure break detection

        corners_ok = charuco_corners is not None and len(charuco_corners) > 0

        if corners_ok:
            # charuco_ids/charuco_corners can trip an internal cv2 shape
            # assertion here under partial/ambiguous detection even when
            # their Python len() values match (confirmed directly: this
            # raised cv2.error even after guarding on len() equality --
            # the mismatch is at the C++ Mat.total() level, not visible
            # from Python). This is a drawing call, not part of the
            # calibration math (matchImagePoints uses the raw arrays
            # directly), so a failure here is caught and skipped rather
            # than treated as detection having failed.
            try:
                aruco.drawDetectedCornersCharuco(annotated, charuco_corners, charuco_ids)
            except cv2.error:
                pass

        corner_count = len(charuco_corners) if corners_ok else 0
        marker_count = 0 if marker_ids is None else len(marker_ids)

        return {
            "charuco_corners": charuco_corners,
            "charuco_ids": charuco_ids,
            "annotated": annotated,
            "corner_count": corner_count,
            "marker_count": marker_count,
        }

    def capture_frame(self, frame: np.ndarray, min_corners: int = 6) -> dict:
        """
        Detects the board in `frame`; if enough corners are found, adds
        this view to the accumulated calibration dataset. Returns the
        same dict as detect(), plus 'added' and 'total_captures'.
        """
        result = self.detect(frame)
        added = False

        if result["corner_count"] >= min_corners:
            obj_pts, img_pts = self.board.matchImagePoints(
                result["charuco_corners"], result["charuco_ids"]
            )

            if obj_pts is not None and len(obj_pts) >= min_corners:
                self.object_points_list.append(obj_pts)
                self.image_points_list.append(img_pts)
                self.capture_corner_counts.append(result["corner_count"])
                self.image_size = (frame.shape[1], frame.shape[0])
                added = True

        result["added"] = added
        result["total_captures"] = len(self.object_points_list)
        return result

    def clear(self) -> None:
        self.object_points_list = []
        self.image_points_list = []
        self.capture_corner_counts = []

    @property
    def capture_count(self) -> int:
        return len(self.object_points_list)

    def calibrate(self, min_views: int = MIN_CALIBRATION_VIEWS) -> dict:
        if self.capture_count < min_views:
            raise RuntimeError(
                f"Need at least {min_views} captured views, have "
                f"{self.capture_count}. Capture more frames from "
                f"different angles/positions/distances before calibrating."
            )

        if self.image_size is None:
            raise RuntimeError("No captured frames to determine image size.")

        width, height = self.image_size

        # Starting cv2.calibrateCamera from None (its own internal guess)
        # is what let fx/fy diverge to ~5500 on a 4-view dataset -- with
        # few/clustered views the solver has too little constraint to find
        # its way back from a bad initial guess. fx=fy=width, cx/cy centered
        # is the standard rule-of-thumb starting point for a normal
        # (non-fisheye) lens; CALIB_FIX_ASPECT_RATIO also holds fx/fy equal
        # throughout the solve (true for this sensor's square pixels),
        # removing one degree of freedom the fit doesn't need.
        initial_camera_matrix = np.array(
            [
                [width, 0.0, width / 2.0],
                [0.0, width, height / 2.0],
                [0.0, 0.0, 1.0],
            ]
        )
        flags = cv2.CALIB_USE_INTRINSIC_GUESS | cv2.CALIB_FIX_ASPECT_RATIO

        reprojection_error, camera_matrix, dist_coeffs, _, _ = cv2.calibrateCamera(
            self.object_points_list,
            self.image_points_list,
            self.image_size,
            initial_camera_matrix,
            None,
            flags=flags,
        )

        warning = _sanity_check_calibration(camera_matrix, dist_coeffs, self.image_size)

        result = {
            "reprojection_error": float(reprojection_error),
            "camera_matrix": camera_matrix.tolist(),
            "dist_coeffs": dist_coeffs.flatten().tolist(),
            "image_size": list(self.image_size),
            "num_captures": self.capture_count,
            "board_params": {
                "squares_x": self.squares_x,
                "squares_y": self.squares_y,
                "square_length_mm": self.square_length_mm,
                "marker_length_mm": self.marker_length_mm,
                "dictionary_name": self.dictionary_name,
                "legacy_pattern": self.legacy_pattern,
            },
        }

        if warning is not None:
            result["warning"] = warning

        return result


def _sanity_check_calibration(
    camera_matrix: np.ndarray, dist_coeffs: np.ndarray, image_size: tuple[int, int]
) -> str | None:
    """
    Returns a human-readable warning if the result looks physically
    implausible (overfit), or None if it looks reasonable. Reprojection
    error alone doesn't catch overfitting -- a model fit to too few/too
    similar views can match those points closely while still being
    nonsense everywhere else, which is exactly what produced the
    fx~5500/k3~-39896 result this is meant to catch on the next run.
    Bounds below are generous (real normal-FOV lenses land well inside
    them) specifically so this only fires on genuinely broken fits, not
    borderline-but-valid ones.
    """
    width, height = image_size
    fx, fy = camera_matrix[0, 0], camera_matrix[1, 1]
    k1, k2, p1, p2, k3 = (dist_coeffs.flatten().tolist() + [0, 0, 0, 0, 0])[:5]

    reasons = []

    if not (0.2 * width <= fx <= 4.0 * width):
        reasons.append(f"focal length fx={fx:.0f} is implausible for a {width}px-wide image")

    if abs(k1) > 5 or abs(k2) > 20 or abs(k3) > 100:
        reasons.append(
            f"distortion coefficients are far outside a normal lens's range "
            f"(k1={k1:.2f}, k2={k2:.2f}, k3={k3:.2f})"
        )

    if not reasons:
        return None

    return (
        "This calibration looks overfit, not correct: " + "; ".join(reasons) + ". "
        "This usually means too few captured views, or views that are too "
        "similar to each other (same distance/angle, not covering the "
        "frame's edges and corners). Clear captures and redo with at "
        f"least {MIN_CALIBRATION_VIEWS} views spread across the whole "
        "frame -- close/far, tilted in different directions, touching "
        "each corner and edge -- before trusting this."
    )


def save_calibration(data: dict, path: Path = DEFAULT_CALIBRATION_PATH) -> None:
    with open(Path(path), "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def load_calibration(path: Path = DEFAULT_CALIBRATION_PATH) -> dict | None:
    path = Path(path)

    if not path.exists():
        return None

    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def build_undistort_maps(calibration: dict):
    """
    Precomputes remap maps once, so applying undistortion to every live
    frame (the Live Camera tab's "Show Undistorted" toggle) is a cheap
    cv2.remap() per frame rather than recomputing the same maps inside
    cv2.undistort() on every single call.
    """
    camera_matrix = np.array(calibration["camera_matrix"])
    dist_coeffs = np.array(calibration["dist_coeffs"])
    width, height = calibration["image_size"]

    new_camera_matrix, _ = cv2.getOptimalNewCameraMatrix(
        camera_matrix, dist_coeffs, (width, height), alpha=1, newImgSize=(width, height)
    )

    map1, map2 = cv2.initUndistortRectifyMap(
        camera_matrix, dist_coeffs, None, new_camera_matrix, (width, height), cv2.CV_16SC2
    )

    return map1, map2


def undistort_with_maps(frame: np.ndarray, maps) -> np.ndarray:
    map1, map2 = maps
    return cv2.remap(frame, map1, map2, interpolation=cv2.INTER_LINEAR)


def crop_edges(
    frame: np.ndarray,
    top_pct: float,
    bottom_pct: float,
    left_pct: float,
    right_pct: float,
) -> np.ndarray:
    """
    Crops a percentage off each edge independently -- meant to be applied
    after undistort_with_maps(): the region built up with alpha=1 in
    build_undistort_maps() (kept to preserve full field of view) includes
    the least-trustworthy pixels near the border, where the calibration
    had the least data coverage and any remaining warping is most visible.
    Percentages, not fixed pixel counts, so this holds up if the frame
    resolution changes.

    Each pair (top/bottom, left/right) is clamped so at least 10% of that
    dimension always remains -- protects against a degenerate/empty crop
    if both sliders on one axis are pushed high at the same time.
    """
    height, width = frame.shape[:2]

    top_pct = max(0.0, min(top_pct, 90.0))
    bottom_pct = max(0.0, min(bottom_pct, 90.0))
    if top_pct + bottom_pct > 90.0:
        scale = 90.0 / (top_pct + bottom_pct)
        top_pct *= scale
        bottom_pct *= scale

    left_pct = max(0.0, min(left_pct, 90.0))
    right_pct = max(0.0, min(right_pct, 90.0))
    if left_pct + right_pct > 90.0:
        scale = 90.0 / (left_pct + right_pct)
        left_pct *= scale
        right_pct *= scale

    top = int(height * top_pct / 100.0)
    bottom = int(height * bottom_pct / 100.0)
    left = int(width * left_pct / 100.0)
    right = int(width * right_pct / 100.0)

    return frame[top : height - bottom, left : width - right]
